# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = 'ubuntu-dev'

    #config.vm.synced_folder "/Users/gopass2002/Lavender", "/home/lavender/Lavender", disabled: false, owner: "lavender", group: "lavender"
    #config.vm.synced_folder "/Users/gopass2002/virtualenvs/lavender", "/home/lavender/env", disabled: false, owner: "lavender", group: "lavender"

    config.vm.provision "shell", path: "provision.sh"
    
    # Hadoop NameNode
    config.vm.network "forwarded_port", guest: 50070, host: 50070
    # Hadoop DameNode
    config.vm.network "forwarded_port", guest: 50075, host: 50075
    # Hadoop JobTracker
    config.vm.network "forwarded_port", guest: 50030, host: 50030
    # Hadoop Node Manager
    config.vm.network "forwarded_port", guest: 8042, host: 8042
    # Hadoop Resource Manager
    config.vm.network "forwarded_port", guest: 8088, host: 8088
    # SSH
    config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disable: true
    # Channel in, out, control
    config.vm.network "forwarded_port", guest: 5540, host: 5540
    config.vm.network "forwarded_port", guest: 5541, host: 5541
    config.vm.network "forwarded_port", guest: 5542, host: 5542
    # MongoDB
    config.vm.network "forwarded_port", guest: 27017, host: 27017
    # Docker Registry
    config.vm.network "forwarded_port", guest: 5000, host: 5500
    # Docker
    config.vm.network "forwarded_port", guest: 4243, host: 4243
    # Remote Command Agent
    config.vm.network "forwarded_port", guest: 8008, host: 8008
    # zerog collector
    config.vm.network "forwarded_port", guest: 6969, host: 6969
    # cAdvisor web ui
    config.vm.network "forwarded_port", guest: 8080, host: 8080

    # pharos
    config.vm.network "forwarded_port", guest: 2375, host: 2375
    config.vm.network "forwarded_port", guest: 4141, host: 4141
    config.vm.network "forwarded_port", guest: 4242, host: 4242
    config.vm.network "forwarded_port", guest: 4343, host: 4343
    config.vm.network "forwarded_port", guest: 4444, host: 4444
    #config.vm.network "private_network", ip: "192.168.33.10"
    #config.vm.network "public_network"

    #config.ssh.forward_agent = true

    #config.vm.synced_folder "../data", "/vagrant_data"

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "8192"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
end
