/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/opt/anyclick/var/log/radius"
#define LIBDIR		"/opt/anyclick/lib"
#define RADDBDIR	"/opt/anyclick/etc/raddb"
#define RUNDIR		"/opt/anyclick/var/run"
#define SBINDIR		"/opt/anyclick/sbin"
#define RADIR		"/opt/anyclick/var/log/radius/radacct"
